# MySQL（部署环境）
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.config-location=classpath:mysqlConfig/mybatis-config.xml
mybatis.mapper-locations=classpath*:mysqlConfig/mapper/**/*.xml
mybatis.type-aliases-package=com.maozhua.mz.domain
